### ISSUE TITLE
[C -> M] Code Cleanup (Progress Tracker)

### ISSUE THREAD

**Issue by HB9HIL** [wavelog/wavelog#339]
This issue tracks the progress of the 'C -> M' movement. 

Target: 
We want to move all cron functions which are currently located in the controllers move to the/a model. This allows us to call the functions from the 'Cron Manager' directly in PHP with CodeIgniter instead to run a curl, to run a curl, to run a curl....

- [x] Move Function 'clublog/upload'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/408
- [x] Move Function 'eqsl/sync'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: #445 
- [x] Move Function 'hrdlog/upload'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: #509 
- [ ] Move Function 'lotw/lotw_upload'
    - [ ] Move Code 
    - [ ] Test
    - [ ] Check all Functions in WebUI working as before
    - [x] PR: #536 
- [ ] Move Function 'qrz/download'
    - [ ] Move Code 
    - [ ] Test
    - [ ] Check all Functions in WebUI working as before
    - [ ] PR:
- [ ] Move Function 'qrz/upload'
    - [ ] Move Code 
    - [ ] Test
    - [ ] Check all Functions in WebUI working as before
    - [ ] PR:
- [ ] Move Function 'update/dxcc'
    - [ ] Move Code 
    - [ ] Test
    - [ ] Check all Functions in WebUI working as before
    - [ ] PR:
- [x] Move Function 'update/lotw_users'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338
- [x] Move Function 'update/update_clublog_scp'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338
- [x] Move Function 'update/update_dok'
    - [x] Move Code 
    - [x] Test
    - [x] CCheck all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338
- [x] Move Function 'update/update_pota'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338
- [x] Move Function 'update/update_sota'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338
- [x] Move Function 'update/update_wwff'
    - [x] Move Code 
    - [x] Test
    - [x] Check all Functions in WebUI working as before
    - [x] PR: https://github.com/wavelog/wavelog/pull/338

&nbsp;

IF ALL ARE DONE:

- [ ] Change cron/run to direct call instead curl
- [x] Rename "LotW Upload" to "LotW Up- and Download"
- [ ] Change debug view file update

**Comment by HB9HIL** [comment]
First Part: 

Moving 6 of 7 Functions to the all new `Update_model.php`
All functions are working normally as before.

#338

**Comment by HB9HIL** [comment]
This can be closed as the rest was not necessary to move
